[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "function"           # deve combaciare con la cartella/pacchetto che importi
version = "0.1.0"
# (facoltativo)
# dependencies = ["numpy", "torch"]
